version: '3'

services:
  nginx:
    image: phagrancy-nginx:latest
    container_name: phagrancy-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      phagrancy:

  php-fpm:
    image: phagrancy-php-fpm:latest
    container_name: phagrancy-php-fpm
    volumes:
      - "./.env_phagrancy:/srv/phagrancy/.env"
      - "./boxes:/srv/phagrancy/boxes"
    networks:
      phagrancy:

networks:
  phagrancy:
    driver: bridge
